FROM ubuntu:14.04
RUN apt-get update
WORKDIR build

RUN apt-get install -y build-essential qt5-default ccache

WORKDIR /
ADD . /build

ENV CCACHE_DIR=/ccache

RUN cd /build/Server && qmake
RUN cd /build/ServerCtrl && qmake

ENTRYPOINT make install
